### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by oallain** [Jibbarth/Yabb#1]
Hey,

It's normally you have dafault name and description on manifest ?
https://github.com/Jibbarth/Yabb/blob/99f09b6351d8131fd53c9c0fe610ffdef4076eec/app/manifest.json#L4

**Comment by Jibbarth** [comment]
Yeah man, it's for i18n. The appName and appDescription are in **_locales** folder.

See [chrome.i18n](https://developer.chrome.com/apps/i18n)
